load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "telemetry",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
    deps = [
        "//sentry/config",
        "@pypi//opentelemetry_api",
        "@pypi//opentelemetry_sdk",
        "@pypi//opentelemetry_exporter_otlp_proto_grpc",
        "@pypi//opentelemetry_instrumentation_httpx",
    ],
)
